### ISSUE TITLE
Number per env in automatic prune

### ISSUE THREAD

**Issue by r0mflip** [claygregory/serverless-prune-plugin#21]
Can we make the number key accept object so that we can specify values for multiple envs
``` yml
custom:
  prune:
    automatic: true
    number:
      dev: 1
      prod: 3
      other: 3
```
Also supporting old behavior
``` yml
custom:
  prune:
    automatic: true
    number: 3
```

IMHO This helps in a more declarative process in CI/CD

And also if this is acceptable I would like to work on it.

**Comment by claygregory** [comment]
Hi @r0mflip 

Thanks for the idea! I can totally see your use-case. And I appreciate you checking in before beginning implementation. However, I don't think per-environment configuration within-plugin is the right path forward here, as serverless.yml already has pretty powerful [variable resolution](https://www.serverless.com/framework/docs/providers/aws/guide/variables/). I think this functionality is best served through that framework capability.

---

For example, if you prefer to keep per-environment pruning as config inside your project:
```yml
custom:
  prune:
    automatic: true
    number: ${file(./environments.yml):${self:provider.stage}.prune}
```

with environments.yml containing:
```yml
dev:
  prune: 1
stg:
  prune: 3
prd:
  prune: 4
```

You can also reference an environmental variable provided by your CI/CD pipeline, to override a default:
```yml
custom:
  prune:
    automatic: true
    number: ${env:PRUNE_NUMBER, 3}
```

Another common pattern would be to reference configuration from an [SSM Parameter Store](https://www.serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-using-the-ssm-parameter-store) key.

Hope this helps!
